### PR TITLE
First page translation test

### PR DESCRIPTION
**Pull request by wewell**

### CODE REVIEW

**Comment by PrimaryFeather** [comment]
Actually, there's no need to make a fork and create a pull request! You can simply clone the [actual repository](https://github.com/Starling-Manual/Starling-Manual-ZH) and commit + push right away. You have full access to that repository — that should make thinks easier for you.

**Comment by PrimaryFeather** [comment]
Looking great already, though! 👍 
→ http://manual.starling-framework.org/zh/

**Comment by wewell** [comment]
Thank you, daniel，well, I understand
I will clone the actual repository and commit + push right away.

**Comment by PrimaryFeather** [comment]
Perfect! You can do it in whatever way works best for you, of course — but I guess it's easiest to work right with that original repository.

Keep up the great work, and thanks again for your efforts!

**Pull request merged**
